name: pytorch
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=hcfcfb64_5
  - ca-certificates=2024.2.2=h56e8100_0
  - libffi=3.4.2=h8ffe710_5
  - libsqlite=3.45.2=hcfcfb64_0
  - libzlib=1.2.13=hcfcfb64_5
  - openssl=3.2.1=hcfcfb64_1
  - python=3.9.19=h4de0772_0_cpython
  - tk=8.6.13=h5226925_1
  - ucrt=10.0.22621.0=h57928b3_0
  - vc=14.3=hcf57466_18
  - vc14_runtime=14.38.33130=h82b7239_18
  - vs2015_runtime=14.38.33130=hcb4865c_18
  - xz=5.2.6=h8d14728_0
  - pip:
    - asttokens==2.4.1
    - attrs==24.2.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.3
    - bleach==6.2.0
    - certifi==2024.8.30
    - cffi==1.17.0
    - cftime==1.6.4
    - charset-normalizer==3.4.0
    - click==8.1.7
    - cloudpickle==1.2.2
    - colorama==0.4.6
    - contourpy==1.2.1
    - cryptography==42.0.8
    - cycler==0.12.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docopt==0.6.2
    - et-xmlfile==1.1.0
    - executing==2.1.0
    - farama-notifications==0.0.4
    - fastjsonschema==2.20.0
    - filelock==3.13.1
    - flwr==1.10.0
    - fonttools==4.53.1
    - fsspec==2024.2.0
    - gputil==1.4.0
    - grpcio==1.65.4
    - gym==0.13.0
    - gym-notices==0.0.8
    - gymnasium==0.29.1
    - idna==3.10
    - importlib-metadata==8.0.0
    - importlib-resources==6.4.0
    - intel-openmp==2021.4.0
    - ipython==8.12.3
    - iterators==0.0.2
    - jedi==0.19.2
    - jinja2==3.1.3
    - joblib==1.4.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - jupyterlab-pygments==0.3.0
    - kiwisolver==1.4.5
    - line-profiler==4.1.3
    - llvmlite==0.39.1
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.4.3
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - mistune==3.0.2
    - mkl==2021.4.0
    - mpmath==1.3.0
    - nbclient==0.10.0
    - nbconvert==7.16.4
    - nbformat==5.10.4
    - netcdf4==1.7.1.post2
    - networkx==3.2.1
    - nltk==3.9.1
    - numba==0.56.3
    - numpy==1.22.4
    - openpyxl==3.1.5
    - orjson==3.10.6
    - packaging==24.1
    - pandas==1.5.2
    - pandocfilters==1.5.1
    - parso==0.8.4
    - pathspec==0.12.1
    - pickleshare==0.7.5
    - pillow==10.2.0
    - pip==24.2
    - platformdirs==4.3.6
    - prompt-toolkit==3.0.48
    - protobuf==4.25.4
    - psutil==6.0.0
    - pure-eval==0.2.3
    - pycparser==2.22
    - pycryptodome==3.20.0
    - pyglet==2.0.16
    - pygments==2.18.0
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - pywin32==308
    - pyzmq==26.2.0
    - referencing==0.35.1
    - regex==2024.7.24
    - requests==2.32.3
    - rich==13.7.1
    - rpds-py==0.21.0
    - scikit-fuzzy==0.4.2
    - scipy==1.7.0
    - setuptools==65.5.1
    - shellingham==1.5.4
    - shimmy==0.2.1
    - six==1.16.0
    - soupsieve==2.6
    - stable-baselines3==2.3.2
    - stack-data==0.6.3
    - sympy==1.12
    - tbb==2021.11.0
    - tinycss2==1.4.0
    - tomli==2.0.1
    - tomli-w==1.0.0
    - torch==2.3.1+cu121
    - torchaudio==2.3.1+cu121
    - torchvision==0.18.1+cu121
    - tornado==6.4.2
    - tqdm==4.66.5
    - traitlets==5.14.3
    - typer==0.9.4
    - typing-extensions==4.9.0
    - tzdata==2024.1
    - urllib3==2.2.3
    - wcwidth==0.2.13
    - webencodings==0.5.1
    - wheel==0.38.4
    - wrapt==1.16.0
    - yarg==0.1.9
    - zipp==3.19.2
prefix: C:\Data\Software\anaconda\envs\pytorch
